name: Deploy papilene

on:
    push:
        branches:
            - main

jobs:
    hello_word:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install Dependecies
              run: npm install --no-audit --no-found --no-optional
            - name: Run linter
              run: npm run lint:check
