name: Papilene Basic

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    hello_word:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install Dependecies
              run: npm ci
            - name: Build
              if: ${{ github.event_name == 'push' }}
              run: npm run build
            - name: Run linter
              run: npm run lint:check
            - name: Testing
              run: npm run test
            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  command: npm run cypress:open
                  start: npm run dev
                  wait-on: http://localhost:5173/
